In [1]:
#Question 1
#Output of the follwoing code
import numpy as np
a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])
c = a + b
c = c * a
print(c[1])
#Ans 10

10


In [2]:
#Question 2
#Assume 
list1 = [1,2,3,4,5,6] # which of the following statement is incorrect
#
# option B 
list1 += 11
print(list1)

TypeError: 'int' object is not iterable

In [15]:
#Question 3
#Ouput of the follwoing code
a = np.array ([[1,2,3], [4,5,6], [7,8,9]])
b = np.eye(3, k=1, dtype=int)
c = np.ones((3,3), dtype=int)
d = a+b+c
print(d[1][2])
#Ans 8

8


In [12]:
#Question 4
#Output of the following code
list1 = [1,2,3,4,5,6,7,8,9]
print(list1[4:len(list1):-2])
#Ans []

[]


In [6]:
#Question 5
#Output of the following code
import pandas as pd
data = pd.Series(['a','b','c','d','e'], index=[1,3,4,6,8])
data[1:4]

3    b
4    c
6    d
dtype: object

In [15]:
#Question 6
#Output of the following code
list1 = [-1,63,36,100,-6,-36]
list1.sort()
print(list1)
#Ans [-36, -6, -1, 36, 63, 100]

[-36, -6, -1, 36, 63, 100]


In [18]:
#Question 7
#Ouput of the following code
list1 = [1,10,3,6]
list2 = [item* 2 for item in list1 if item > 5]
print(list2)
#ans [20, 12]

[20, 12]


In [3]:
#Question 8
#ouput of the following code
mystr = 'yes'
yourstr = 'no'
mystr +=  yourstr * 2
print(mystr)

yesnono


In [27]:
#Question 9
#output of the following code? Invalid python?
password = 'ILOVEPYTHON'

if password.isalpha():
    print ('invalid, must contain 1 digit')
elif password.isdigit():
    print ('invalid2')
elif password.isupper():
    print ('invalid3')
else: 
    print ('your password is secure')


#-->Ans Invalid, cannot all uppercase

invalid, must contain 1 digit


In [8]:
# Question 10
#the output of the following code?
arr = np.array(np.arange(9).reshape(3,3))
print(arr.sum())

36


In [20]:
#Question 11 
#Output of the following code
msg = '03/07/2022'
result = msg.split('/')
print(result)
#ans ['03', '07', '2022']

['03', '07', '2022']


In [31]:
#Question 12
d1 = {1:10, 2:20, 3:30}
d2 = {v:k * 3 for k,v in d1.items()}
print(d2)
#(10:3, 20:6, 30:9) 

{10: 3, 20: 6, 30: 9}


In [32]:
#Question 13
#citer question?
cities = {'Georgia' :'Atlanta' , 'CA': 'Berkly' , 'New York': 'Alabama'}
if 'CA' in cities:
    del cities['CA']
    cities['CA'] = 'Sacramento'
print(cities)

#Ans --> {'Georgia': 'Atlanta', 'New York': 'Alabama', 'CA': 'Sacramento'}

{'Georgia': 'Atlanta', 'New York': 'Alabama', 'CA': 'Sacramento'}


In [23]:
#Question 14
#Ouput of the folowing code
arr = np.array([1,2,3,4,5,6])
arr[2] = 3.14
print(arr)

[1 2 3 4 5 6]


In [25]:
#Question 15
#Ouput of the follwoing code
s1 = [1,2,3,4,5,6]
s1_sub = s1[1:3]
s1_sub[0]
print(s1)

[1, 2, 3, 4, 5, 6]


In [29]:
#Question 16 
# output of the following code for axis = 1
a = ([1,2],
     [3,4])
np.concatenate((a,a),axis = 1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [30]:
#Question 16 
# output of the following code for axis = 1
for axis 0
a = ([1,2],
     [3,4])
np.concatenate((a,a),axis = 0)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [38]:
#Question 17
#what will be the output for the follwoing code
list1 = [0,1,2,3,4,5,6,7,8,9]
print(list1[5::-2])

[5, 3, 1]


In [42]:
#Question 18
arr = np.array([9])
ind = np.array([3])([6])
print(arr(ind))
#Ans [3][6]

TypeError: 'numpy.ndarray' object is not callable

In [26]:
#Question 19
#what will be the output for the follwoing code
arr1 = np.array([True, False, True])
arr2 = np.array([False, True, False])
print(arr1 or arr2)
#Ans B - [FALSE,FALSE,FALSE]

[ True  True  True]


In [21]:
arr1 = np.array([True, False, True])
arr2 = np.array([False, True, False])
print(arr1 or arr2)


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [25]:
#Question 20
#what will be the output for the follwoing code
import pandas as pd
ser = pd.Series({2:'a', 1:'b', 3:'c'}, index = {3,2})
print(ser)
#Ans B

2    a
3    c
dtype: object


In [64]:
#Question 21
#What is the correct syntax to print the number 8 from the array below
arr = np.array(([1,2,3,4,5], [6,7,8,9,10]))
print(arr[1,2])
#Ans print(arr[1,2]) - A

8


In [13]:
#Question 22
#What is the correct syntax to print the numbers [3,4,5] from the below
arr = np.array([1,2,3,4,5,6,7])
print(arr[2:5])
#Ans print(arr[2:5]) - B

[3 4 5]


In [15]:
#Question 23
#Which syntax would print the last 4 numbers from hr array below
arr = np.array([1,2,3,4,5,6,7])
print(arr[3:])
#Ans print(arr[3:]) - B

[4 5 6 7]


In [18]:
#Question 24
#Which syntax would print every other item from the array below
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])
#Ans print(arr[::2]) - A

[1 3 5 7]


In [ ]:
#Question 25
#In numpy, what does the attributes shape of an array mean?
# - The shape of an array is the number of elements in each dimension. ans b

In [83]:
#Question 26
#What is output of the follwoing code
arr = np.array([1,2,3])
print(np.cumsum(arr))
#Ans - [1 3 6]

[1 3 6]


In [85]:
#Question 27
#what will be output for the follwoing code
arr = np.array([1,2,3,4,5,6])
print(np.where(arr <=3, 0, arr))
#Ans [ 0 0 0 4 5 6]

[0 0 0 4 5 6]


In [16]:
#Question 28
#Output of the follwing code
arr = np.arange(6).reshape(2,3)
raveled = arr.ravel()
raveled[0] = 99
print(arr)
#Ans 

[[99  1  2]
 [ 3  4  5]]


In [89]:
#Question 29
#what will be output of the following code
data = pd.Series([1,np.nan, 'hello', None])
result = data[data.notnull()]
print(result)

0        1
2    hello
dtype: object


In [91]:
#Question 30
#Ouput of the following code
obj = pd.Series(range(5), index=['a','a','b','b','c'])
obj['b']

b    2
b    3
dtype: int64